#Cluster Sentiment Analysis Project, CCC2018-35, Melbourne
#Members: Yan Jiang 816920, Yijiang Liu 848008, Zihua Liu 857673, Zhenxiang Wang 879694, Lingtao Jiang 867583

---
- name: Make file system
  filesystem:
    fstype: ext4
    dev: /dev/vdc

- name: Create mount point
  file:
    path: /mnt/database
    state: directory

- name: Mount up device
  mount:
    name: /mnt/database
    src: /dev/vdc
    fstype: ext4
    state: mounted