#Cluster Sentiment Analysis Project, CCC2018-35, Melbourne
#Members: Yan Jiang 816920, Yijiang Liu 848008, Zihua Liu 857673, Zhenxiang Wang 879694, Lingtao Jiang 867583

---
- name: install pip3
  apt:
    name:
      - git
      - python3-pip
      - libopenmpi-dev
      - python3-dev
    state: latest
    install_recommends: no

- name: Install setuptools
  command: sudo pip3 install --upgrade setuptools

- name: Python3 Libs
  pip:
    name:
      - couchdb
      - textblob
      - tweepy
      - nltk
      - vaderSentiment
      - flask
      - numpy
      - geojson_utils
      - mpi4py
    executable: pip3
  become: true    

- name: Clone from GitHub
  git:
    repo: "https://github.com/lotharJiang/Cluster-Sentiment-Analysis"
    dest: "/mnt/database/Cluster-Setiment-Analysis"
    clone: yes
    force: yes
