#Cluster Sentiment Analysis Project, CCC2018-35, Melbourne
#Members: Yan Jiang 816920, Yijiang Liu 848008, Zihua Liu 857673, Zhenxiang Wang 879694, Lingtao Jiang 867583

---
- name: Launch new instance(s)
  os_server:
    state: present
    auth:
      auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
      username: y.liu275@student.unimelb.edu.au
      password: YmU3ZmFjMjJlYjgyZmYy
      project_name: CCC2018-35
    name: "{{item}}"
    image: NeCTAR Ubuntu 16.04 LTS (Xenial) amd64
    key_name: "{{key}}"
    availability_zone: melbourne-qh2
    timeout: 200
    flavor: "1"
    security_groups: default
  with_sequence: start={{start}} end={{end}} format=node%x
  register: instances

- name: Create volume
  os_volume:
    auth:
      auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
      username: y.liu275@student.unimelb.edu.au
      password: YmU3ZmFjMjJlYjgyZmYy
      project_name: CCC2018-35
    state: present
    availability_zone: melbourne-qh2
    size: "{{volume}}"
    display_name: "{{item}}"
  with_sequence: start={{start}} end={{end}} format=volume%x

- name: Attach volume to instance
  os_server_volume:
    auth:
      auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
      username: y.liu275@student.unimelb.edu.au
      password: YmU3ZmFjMjJlYjgyZmYy
      project_name: CCC2018-35
    state: present
    server: "node{{item}}"
    volume: "volume{{item}}"
  with_sequence: start={{start}} end={{end}}

- name: Register the new instances to be a group
  add_host:
    hostname: "{{item.openstack.interface_ip}}"
    groups: 
      - instanceGroup
  with_items: "{{instances.results}}"
  
- name: Register the master node to be a group
  add_host:
    hostname: "{{master}}"
    groups:
      - masterGroup

